[phases.build]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "pnpm next build"
]

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3000"
